spring:
  application:
    name: Edu-Tracking-System

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Mail Configuration

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  # ehcache config
  cache:
    jcache:
      config: "classpath:ehcache.xml"

#Jwt configuration
myapp:
  jwt:
    secret: ${JWT_SECRET}
    access_expiry: 5
    refresh_expiry: 1440

# Application Configuration
super_admin:
  email: ${SUPER-ADMIN_EMAIL}


